[package]
name = "pdftrim"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.25"
lopdf = "0.35.0"
regex = "1.11.1"
