name: CI

on:
  push:
    branches: [main]
    tags: ["**"]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  RUST_TOOLCHAIN: "1.84.1"
  RUST_TOOLCHAIN_RUSTFMT: nightly
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN_RUSTFMT" --component rustfmt
          rustup override set "$RUST_TOOLCHAIN_RUSTFMT"

      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN" --component clippy
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  lockfile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - name: Check if Cargo.lock is up-to-date
        run: cargo tree --depth 1 --no-dedupe --locked

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-24.04
          - target: x86_64-unknown-linux-musl
            runs-on: ubuntu-24.04
          - target: aarch64-apple-darwin
            runs-on: macos-14
          - target: x86_64-apple-darwin
            runs-on: macos-14
    name: build (${{ matrix.target }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN" --target ${{ matrix.target }}
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: cargo build
        run: cargo build --all-targets --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: pdftrim-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/pdftrim
          if-no-files-found: error

  build-linux-cross:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN" --target ${{ matrix.target }}
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cross
        # Set --force to work around https://github.com/Swatinem/rust-cache/issues/204
        run: cargo binstall --force cross

      - name: cross build
        run: cross build --all-targets --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: pdftrim-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/pdftrim
          if-no-files-found: error

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$env:RUST_TOOLCHAIN" --target ${{ matrix.target }}
          rustup override set "$env:RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: cargo build
        run: cargo build --all-targets --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: pdftrim-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/pdftrim.exe
          if-no-files-found: error

  release-create-assets:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - rustfmt
      - clippy
      - lockfile
      - build
      - build-linux-cross
      - build-windows
    runs-on: ubuntu-24.04
    permissions: {}
    outputs:
      signing-pubkey: ${{ steps.create-keypair.outputs.pubkey }}
    steps:
      - name: Setup minisign
        run: |
          mkdir minisign
          curl -fsSL https://github.com/jedisct1/minisign/releases/download/0.12/minisign-0.12-linux.tar.gz | tar -xzC minisign
          echo "$(pwd)/minisign/minisign-linux/x86_64" >> "$GITHUB_PATH"

      - name: Create a key pair
        id: create-keypair
        run: |
          minisign -GW -p signing.pub -s signing.key
          echo "pubkey=$(<signing.pub)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: pdftrim-*
          path: artifacts

      - name: Create release assets
        run: |
          cd artifacts
          for artifact in *; do
            target="${artifact#pdftrim-}"
            asset="pdftrim-$TAG-$target"

            mv "$artifact" "$asset"
            tar -czf "$asset.tar.gz" "$asset"
            rm -rf "$asset"
            minisign -SW -s ../signing.key -x "$asset.tar.gz.sig" -m "$asset.tar.gz"
          done
        env:
          TAG: ${{ github.ref_name }}

      - uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: artifacts/*
          if-no-files-found: error
          compression-level: 0

  release-upload-assets:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - release-create-assets
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: release-assets

      - name: Upload release assets
        run: |
          gh release upload "$TAG" release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}

  release-crates-io:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - release-create-assets
      - release-upload-assets
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - name: Set binstall signing metadata
        run: |
          cat >> Cargo.toml <<EOF
          [package.metadata.binstall.signing]
          algorithm = "minisign"
          pubkey = "$PUBKEY"
          EOF
        env:
          PUBKEY: ${{ needs.release-create-assets.outputs.signing-pubkey }}

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
